### ISSUE TITLE
About climate change data

### ISSUE THREAD

**Issue by yudeqang** [open-meteo/open-data#10]
Do you have plans to release climate climate change models when？

**Comment by patrick-zippenfenig** [comment]
There are no fixed plans yet. What is your use-case for this data?

**Comment by yudeqang** [comment]
I am very interested in long-term climate change, but it is quite costly, and I can only afford to query a few locations each day. Moreover, it seems to be a significant drain on your server resources. Therefore, I would like to ask if you have any plans to release climate change data. Thank you!
