### ISSUE TITLE
Gwan model no longer updates

### ISSUE THREAD

**Issue by libertykite** [open-meteo/open-data#12]
Hi Patrick, 

this message is to inform you that the Gwan model is no longer updated on the S3 server.

https://openmeteo.s3.amazonaws.com/index.html#data/dwd_gwam/wave_height/

**Comment by libertykite** [comment]
@patrick-zippenfenig  Any news on this ?

**Comment by patrick-zippenfenig** [comment]
No, see https://github.com/open-meteo/open-meteo/issues/819

**Comment by libertykite** [comment]
Thanks for the feedback !

And so do you intend to put the other wave models on the S3 server?

**Comment by patrick-zippenfenig** [comment]
I will consider to add additional wave model as open-data. I do not want to push data on AWS if those models did not provide reliable updates. The new wave models have been integrated just over the last 2 weeks.

**Comment by patrick-zippenfenig** [comment]
All wave models are now in the open-data distribution
