### ISSUE TITLE
Identifying how each variable is calculated

### ISSUE THREAD

**Issue by jovanovski** [open-meteo/open-data#13]
Is there an easy way to identify which data points are needed to calculate a variable (for example `snowfall`), and then discover which models have them in order to download just them?

**Comment by patrick-zippenfenig** [comment]
The easiest is just to click through all models and search for "snowfall". Some models like DWD ICON split snowfall into large scale and convective snowfall. Both are required.

![Screenshot 2024-07-01 at 11 13 41](https://github.com/open-meteo/open-data/assets/11670456/df40cdf3-872f-45bc-ac89-6580649a6766)

https://openmeteo.s3.amazonaws.com/index.html#data/
