### ISSUE TITLE
Build an environment to obtain weather model data without Docker

### ISSUE THREAD

**Issue by tokiyui** [open-meteo/open-data#21]
The following page describes how to obtain weather model data.
https://github.com/open-meteo/open-data/tree/main/tutorial_weather_api

The method described here seems to use Docker, but is there a way to run it without Docker and with just pure Python commands such as pip?

**Comment by patrick-zippenfenig** [comment]
Hi. No this is not possible. Open-Meteo is written in Swift and C. A couple of libraries are also required which are bundled in the Docker images. Maybe at some point in the future, we add Python bindings to use Open-Meteo directly in Python, but there are no plans yet.
