### ISSUE TITLE
Wind Data is not aviable for ERA5-Land

### ISSUE THREAD

**Issue by johhartm** [open-meteo/open-data#4]
Hi there, I stumbled upon this very intersting servicethat could be really helpful for me. However, I need the wind data with 9km grid resolution that is only aviable through ERA5-Land. Would it be possible to also provide this data?

**Comment by patrick-zippenfenig** [comment]
Hi, wind data from ERA5-Land in 0.1° resolution is equivalent to interpolated wind data from ERA5 in 0.25°. This is explained in the ERA5-Land documentation that atmospheric parameter are used as forcing. 

The Open-Meteo [historical weather api](https://open-meteo.com/en/docs/historical-weather-api/) also integrates ECMWF IFS at 9 km resolution with data from 2017 onwards, but this data is not yet available through this open-data distribution

**Comment by johhartm** [comment]
@patrick-zippenfenig Unfortionally this solution proved to be less stable than anticipated... It would be really usefull if you could point out how the spatial interpolation is done since I only can find information on a package that has been developed for this reason but cant find any information on how to download and use it
