### ISSUE TITLE
EMCWF Wind Gusts Not Working

### ISSUE THREAD

**Issue by alexcittadini** [open-meteo/open-data#9]
Wind Gusts appear to be missing from the ECMWF forecast. 

A test request on the documentation page below will return wind speed and direction but not gusts. 

https://open-meteo.com/en/docs/ecmwf-api#hourly=wind_speed_10m,wind_direction_10m,wind_gusts_10m&wind_speed_unit=kn

**Comment by patrick-zippenfenig** [comment]
Unfortunately that is an issue in the documentation. No wind gust data is available for ECMWF IFS open-data. I just [updated the documentation](https://github.com/open-meteo/open-meteo-website/commit/1d9ce2c8e5d8514b57b77913481cd1bb9a7534ca).
